{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome! This command will take you through the configuration of gcloud.\n",
      "\n",
      "Your current configuration has been set to: [default]\n",
      "\n",
      "You can skip diagnostics next time by using the following flag:\n",
      "  gcloud init --skip-diagnostics\n",
      "\n",
      "Network diagnostic detects and fixes local network connection issues.\n",
      "Checking network connection...done.                                            \n",
      "Reachability Check passed.\n",
      "Network diagnostic passed (1/1 checks passed).\n",
      "\n",
      "You must log in to continue. Would you like to log in (Y/n)?  ^C\n",
      "\n",
      "\n",
      "Command killed by keyboard interrupt\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!gcloud init"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "GCS_BUCKET='es_kiff'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "trainRecordPath = '/u01/notebooks/TFM/DatasetCreator/out/train.record'\n",
    "testRecordPath = '/u01/notebooks/TFM/DatasetCreator/out/test.record'\n",
    "labelsPath = '/u01/notebooks/TFM/DatasetCreator/out/label_map.pbtxt'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Copying file:///u01/notebooks/TFM/DatasetCreator/out/train.record [Content-Type=application/octet-stream]...\n",
      "- [1 files][ 65.7 MiB/ 65.7 MiB]    4.4 MiB/s                                   \n",
      "Operation completed over 1 objects/65.7 MiB.                                     \n",
      "Copying file:///u01/notebooks/TFM/DatasetCreator/out/test.record [Content-Type=application/octet-stream]...\n",
      "| [1 files][ 18.9 MiB/ 18.9 MiB]                                                \n",
      "Operation completed over 1 objects/18.9 MiB.                                     \n",
      "Copying file:///u01/notebooks/TFM/DatasetCreator/out/label_map.pbtxt [Content-Type=application/octet-stream]...\n",
      "- [1 files][  499.0 B/  499.0 B]                                                \n",
      "Operation completed over 1 objects/499.0 B.                                      \n"
     ]
    }
   ],
   "source": [
    "!gsutil cp $trainRecordPath gs://$GCS_BUCKET/data/\n",
    "!gsutil cp $testRecordPath gs://$GCS_BUCKET/data/\n",
    "!gsutil cp $labelsPath gs://$GCS_BUCKET/data/label_map.pbtxt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--2019-05-09 23:39:02--  http://storage.googleapis.com/download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_11_06_2017.tar.gz\n",
      "Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.210.176, 2a00:1450:4003:801::2010\n",
      "Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.210.176|:80... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 595490113 (568M) [application/x-tar]\n",
      "Saving to: ‘faster_rcnn_resnet101_coco_11_06_2017.tar.gz’\n",
      "\n",
      "faster_rcnn_resnet1 100%[===================>] 567.90M  18.0MB/s    in 34s     \n",
      "\n",
      "2019-05-09 23:39:37 (16.6 MB/s) - ‘faster_rcnn_resnet101_coco_11_06_2017.tar.gz’ saved [595490113/595490113]\n",
      "\n",
      "faster_rcnn_resnet101_coco_11_06_2017/\n",
      "faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.index\n",
      "faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.meta\n",
      "faster_rcnn_resnet101_coco_11_06_2017/frozen_inference_graph.pb\n",
      "faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.data-00000-of-00001\n",
      "faster_rcnn_resnet101_coco_11_06_2017/graph.pbtxt\n",
      "Copying file://faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.data-00000-of-00001 [Content-Type=application/octet-stream]...\n",
      "==> NOTE: You are uploading one or more large file(s), which would run          \n",
      "significantly faster if you enable parallel composite uploads. This\n",
      "feature can be enabled by editing the\n",
      "\"parallel_composite_upload_threshold\" value in your .boto\n",
      "configuration file. However, note that if you do this large files will\n",
      "be uploaded as `composite objects\n",
      "<https://cloud.google.com/storage/docs/composite-objects>`_,which\n",
      "means that any user who downloads such objects will need to have a\n",
      "compiled crcmod installed (see \"gsutil help crcmod\"). This is because\n",
      "without a compiled crcmod, computing checksums on composite objects is\n",
      "so slow that gsutil disables downloads of composite objects.\n",
      "\n",
      "Copying file://faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.index [Content-Type=application/octet-stream]...\n",
      "Copying file://faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.meta [Content-Type=application/octet-stream]...\n",
      "| [3 files][435.9 MiB/435.9 MiB]    3.2 MiB/s                                   \n",
      "Operation completed over 3 objects/435.9 MiB.                                    \n"
     ]
    }
   ],
   "source": [
    "!wget http://storage.googleapis.com/download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_11_06_2017.tar.gz\n",
    "!tar -xvf faster_rcnn_resnet101_coco_11_06_2017.tar.gz\n",
    "!gsutil cp faster_rcnn_resnet101_coco_11_06_2017/model.ckpt.* gs://$GCS_BUCKET/data/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Copying file:///u01/notebooks/TFM/Configs/rfcn_resnet101GCP.config [Content-Type=application/octet-stream]...\n",
      "/ [1 files][  3.5 KiB/  3.5 KiB]                                                \n",
      "Operation completed over 1 objects/3.5 KiB.                                      \n"
     ]
    }
   ],
   "source": [
    "!sed -i \"s|PATH_TO_BE_CONFIGURED|\"gs://$GCS_BUCKET\"/data|g\"  /u01/notebooks/TFM/Configs/rfcn_resnet101GCP.config\n",
    "!gsutil cp /u01/notebooks/TFM/Configs/rfcn_resnet101GCP.config gs://$GCS_BUCKET/data/rfcn_resnet101GCP.config\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/u01/notebooks/models/research\n"
     ]
    }
   ],
   "source": [
    "cd /u01/notebooks/models/research/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into 'cocoapi'...\n",
      "remote: Enumerating objects: 953, done.\u001b[K\n",
      "remote: Total 953 (delta 0), reused 0 (delta 0), pack-reused 953\n",
      "Receiving objects: 100% (953/953), 11.70 MiB | 1.66 MiB/s, done.\n",
      "Resolving deltas: 100% (566/566), done.\n",
      "running sdist\n",
      "running egg_info\n",
      "creating object_detection.egg-info\n",
      "writing object_detection.egg-info/PKG-INFO\n",
      "writing dependency_links to object_detection.egg-info/dependency_links.txt\n",
      "writing requirements to object_detection.egg-info/requires.txt\n",
      "writing top-level names to object_detection.egg-info/top_level.txt\n",
      "writing manifest file 'object_detection.egg-info/SOURCES.txt'\n",
      "reading manifest file 'object_detection.egg-info/SOURCES.txt'\n",
      "writing manifest file 'object_detection.egg-info/SOURCES.txt'\n",
      "running check\n",
      "warning: check: missing required meta-data: url\n",
      "\n",
      "warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied\n",
      "\n",
      "creating object_detection-0.1\n",
      "creating object_detection-0.1/object_detection\n",
      "creating object_detection-0.1/object_detection.egg-info\n",
      "creating object_detection-0.1/object_detection/anchor_generators\n",
      "creating object_detection-0.1/object_detection/box_coders\n",
      "creating object_detection-0.1/object_detection/builders\n",
      "creating object_detection-0.1/object_detection/core\n",
      "creating object_detection-0.1/object_detection/data_decoders\n",
      "creating object_detection-0.1/object_detection/dataset_tools\n",
      "creating object_detection-0.1/object_detection/inference\n",
      "creating object_detection-0.1/object_detection/legacy\n",
      "creating object_detection-0.1/object_detection/matchers\n",
      "creating object_detection-0.1/object_detection/meta_architectures\n",
      "creating object_detection-0.1/object_detection/metrics\n",
      "creating object_detection-0.1/object_detection/models\n",
      "creating object_detection-0.1/object_detection/models/keras_models\n",
      "creating object_detection-0.1/object_detection/predictors\n",
      "creating object_detection-0.1/object_detection/predictors/heads\n",
      "creating object_detection-0.1/object_detection/protos\n",
      "creating object_detection-0.1/object_detection/utils\n",
      "copying files to object_detection-0.1...\n",
      "copying README.md -> object_detection-0.1\n",
      "copying setup.py -> object_detection-0.1\n",
      "copying object_detection/__init__.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/eval_util.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/eval_util_test.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/export_inference_graph.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/export_tflite_ssd_graph.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/export_tflite_ssd_graph_lib.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/export_tflite_ssd_graph_lib_test.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/exporter.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/exporter_test.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/inputs.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/inputs_test.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/model_hparams.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/model_lib.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/model_lib_test.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/model_main.py -> object_detection-0.1/object_detection\n",
      "copying object_detection/model_tpu_main.py -> object_detection-0.1/object_detection\n",
      "copying object_detection.egg-info/PKG-INFO -> object_detection-0.1/object_detection.egg-info\n",
      "copying object_detection.egg-info/SOURCES.txt -> object_detection-0.1/object_detection.egg-info\n",
      "copying object_detection.egg-info/dependency_links.txt -> object_detection-0.1/object_detection.egg-info\n",
      "copying object_detection.egg-info/requires.txt -> object_detection-0.1/object_detection.egg-info\n",
      "copying object_detection.egg-info/top_level.txt -> object_detection-0.1/object_detection.egg-info\n",
      "copying object_detection/anchor_generators/__init__.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/grid_anchor_generator.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/grid_anchor_generator_test.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/multiple_grid_anchor_generator.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/multiple_grid_anchor_generator_test.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/multiscale_grid_anchor_generator.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/anchor_generators/multiscale_grid_anchor_generator_test.py -> object_detection-0.1/object_detection/anchor_generators\n",
      "copying object_detection/box_coders/__init__.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/faster_rcnn_box_coder.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/faster_rcnn_box_coder_test.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/keypoint_box_coder.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/keypoint_box_coder_test.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/mean_stddev_box_coder.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/mean_stddev_box_coder_test.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/square_box_coder.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/box_coders/square_box_coder_test.py -> object_detection-0.1/object_detection/box_coders\n",
      "copying object_detection/builders/__init__.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/anchor_generator_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/anchor_generator_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/box_coder_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/box_coder_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/box_predictor_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/box_predictor_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/calibration_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/calibration_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/dataset_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/dataset_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/graph_rewriter_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/graph_rewriter_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/hyperparams_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/hyperparams_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/image_resizer_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/image_resizer_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/input_reader_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/input_reader_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/losses_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/losses_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/matcher_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/matcher_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/model_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/model_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/optimizer_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/optimizer_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/post_processing_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/post_processing_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/preprocessor_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/preprocessor_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/region_similarity_calculator_builder.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/builders/region_similarity_calculator_builder_test.py -> object_detection-0.1/object_detection/builders\n",
      "copying object_detection/core/__init__.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/anchor_generator.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/balanced_positive_negative_sampler.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/balanced_positive_negative_sampler_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/batcher.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/batcher_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_coder.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_coder_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_list.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_list_ops.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_list_ops_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_list_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/box_predictor.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/data_decoder.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/data_parser.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/freezable_batch_norm.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/freezable_batch_norm_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/keypoint_ops.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/keypoint_ops_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/losses.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/losses_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/matcher.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/matcher_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/minibatch_sampler.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/minibatch_sampler_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/model.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/post_processing.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/post_processing_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/prefetcher.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/prefetcher_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/preprocessor.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/preprocessor_cache.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/preprocessor_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/region_similarity_calculator.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/region_similarity_calculator_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/standard_fields.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/target_assigner.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/core/target_assigner_test.py -> object_detection-0.1/object_detection/core\n",
      "copying object_detection/data_decoders/__init__.py -> object_detection-0.1/object_detection/data_decoders\n",
      "copying object_detection/data_decoders/tf_example_decoder.py -> object_detection-0.1/object_detection/data_decoders\n",
      "copying object_detection/data_decoders/tf_example_decoder_test.py -> object_detection-0.1/object_detection/data_decoders\n",
      "copying object_detection/dataset_tools/__init__.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_coco_tf_record.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_coco_tf_record_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_kitti_tf_record.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_kitti_tf_record_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_oid_tf_record.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_pascal_tf_record.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_pascal_tf_record_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/create_pet_tf_record.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/oid_hierarchical_labels_expansion.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/oid_hierarchical_labels_expansion_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/oid_tfrecord_creation.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/oid_tfrecord_creation_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/tf_record_creation_util.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/dataset_tools/tf_record_creation_util_test.py -> object_detection-0.1/object_detection/dataset_tools\n",
      "copying object_detection/inference/__init__.py -> object_detection-0.1/object_detection/inference\n",
      "copying object_detection/inference/detection_inference.py -> object_detection-0.1/object_detection/inference\n",
      "copying object_detection/inference/detection_inference_test.py -> object_detection-0.1/object_detection/inference\n",
      "copying object_detection/inference/infer_detections.py -> object_detection-0.1/object_detection/inference\n",
      "copying object_detection/legacy/__init__.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/legacy/eval.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/legacy/evaluator.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/legacy/train.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/legacy/trainer.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/legacy/trainer_test.py -> object_detection-0.1/object_detection/legacy\n",
      "copying object_detection/matchers/__init__.py -> object_detection-0.1/object_detection/matchers\n",
      "copying object_detection/matchers/argmax_matcher.py -> object_detection-0.1/object_detection/matchers\n",
      "copying object_detection/matchers/argmax_matcher_test.py -> object_detection-0.1/object_detection/matchers\n",
      "copying object_detection/matchers/bipartite_matcher.py -> object_detection-0.1/object_detection/matchers\n",
      "copying object_detection/matchers/bipartite_matcher_test.py -> object_detection-0.1/object_detection/matchers\n",
      "copying object_detection/meta_architectures/__init__.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/faster_rcnn_meta_arch.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/faster_rcnn_meta_arch_test.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/faster_rcnn_meta_arch_test_lib.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/rfcn_meta_arch.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/rfcn_meta_arch_test.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/ssd_meta_arch.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/ssd_meta_arch_test.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/meta_architectures/ssd_meta_arch_test_lib.py -> object_detection-0.1/object_detection/meta_architectures\n",
      "copying object_detection/metrics/__init__.py -> object_detection-0.1/object_detection/metrics\n",
      "copying object_detection/metrics/calibration_evaluation.py -> object_detection-0.1/object_detection/metrics\n",
      "copying object_detection/metrics/calibration_evaluation_test.py -> object_detection-0.1/object_detection/metrics\n",
      "copying object_detection/metrics/calibration_metrics.py -> object_detection-0.1/object_detection/metrics\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "copying object_detection/metrics/calibration_metrics_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/coco_evaluation.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/coco_evaluation_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/coco_tools.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/coco_tools_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/io_utils.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/offline_eval_map_corloc.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/offline_eval_map_corloc_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_od_challenge_evaluation.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_od_challenge_evaluation_utils.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_od_challenge_evaluation_utils_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_vrd_challenge_evaluation.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_vrd_challenge_evaluation_utils.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/oid_vrd_challenge_evaluation_utils_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/tf_example_parser.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/metrics/tf_example_parser_test.py -> object_detection-0.1/object_detection/metrics\r\n",
      "copying object_detection/models/__init__.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/embedded_ssd_mobilenet_v1_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/embedded_ssd_mobilenet_v1_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_inception_v2_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_inception_v2_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_mobilenet_v1_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_mobilenet_v1_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_nas_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_nas_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_pnas_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_pnas_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_resnet_v1_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/faster_rcnn_resnet_v1_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/feature_map_generators.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/feature_map_generators_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_inception_v2_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_inception_v2_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_inception_v3_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_inception_v3_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_fpn_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_fpn_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_keras_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_ppn_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v1_ppn_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v2_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v2_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v2_fpn_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v2_fpn_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_mobilenet_v2_keras_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_pnasnet_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_pnasnet_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_fpn_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_fpn_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_fpn_feature_extractor_testbase.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_ppn_feature_extractor.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_ppn_feature_extractor_test.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/ssd_resnet_v1_ppn_feature_extractor_testbase.py -> object_detection-0.1/object_detection/models\r\n",
      "copying object_detection/models/keras_models/__init__.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/mobilenet_v1.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/mobilenet_v1_test.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/mobilenet_v2.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/mobilenet_v2_test.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/original_mobilenet_v2.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/models/keras_models/test_utils.py -> object_detection-0.1/object_detection/models/keras_models\r\n",
      "copying object_detection/predictors/__init__.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/convolutional_box_predictor.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/convolutional_box_predictor_test.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/convolutional_keras_box_predictor.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/convolutional_keras_box_predictor_test.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/mask_rcnn_box_predictor.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/mask_rcnn_box_predictor_test.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/rfcn_box_predictor.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/rfcn_box_predictor_test.py -> object_detection-0.1/object_detection/predictors\r\n",
      "copying object_detection/predictors/heads/__init__.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/box_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/box_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/class_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/class_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_box_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_box_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_class_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_class_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_mask_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keras_mask_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keypoint_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/keypoint_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/mask_head.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/predictors/heads/mask_head_test.py -> object_detection-0.1/object_detection/predictors/heads\r\n",
      "copying object_detection/protos/__init__.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/anchor_generator_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/argmax_matcher_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/bipartite_matcher_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/box_coder_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/box_predictor_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/calibration_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/eval_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/faster_rcnn_box_coder_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/faster_rcnn_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/graph_rewriter_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/grid_anchor_generator_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/hyperparams_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/image_resizer_pb2.py -> object_detection-0.1/object_detection/protos\r\n",
      "copying object_detection/protos/input_reader_pb2.py -> object_detection-0.1/object_detection/protos\r\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "copying object_detection/protos/keypoint_box_coder_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/losses_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/matcher_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/mean_stddev_box_coder_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/model_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/multiscale_anchor_generator_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/optimizer_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/pipeline_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/post_processing_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/preprocessor_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/region_similarity_calculator_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/square_box_coder_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/ssd_anchor_generator_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/ssd_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/string_int_label_map_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/protos/train_pb2.py -> object_detection-0.1/object_detection/protos\n",
      "copying object_detection/utils/__init__.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/category_util.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/category_util_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/config_util.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/config_util_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/context_manager.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/context_manager_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/dataset_util.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/dataset_util_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/json_utils.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/json_utils_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/label_map_util.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/label_map_util_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/learning_schedules.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/learning_schedules_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/metrics.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/metrics_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_list.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_list_ops.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_list_ops_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_list_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_mask_list.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_mask_list_ops.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_mask_list_ops_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_mask_list_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_ops.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_box_ops_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_mask_ops.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/np_mask_ops_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/object_detection_evaluation.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/object_detection_evaluation_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/ops.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/ops_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/per_image_evaluation.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/per_image_evaluation_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/per_image_vrd_evaluation.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/per_image_vrd_evaluation_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/shape_utils.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/shape_utils_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/static_shape.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/static_shape_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/test_case.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/test_utils.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/test_utils_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/variables_helper.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/variables_helper_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/visualization_utils.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/visualization_utils_test.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/vrd_evaluation.py -> object_detection-0.1/object_detection/utils\n",
      "copying object_detection/utils/vrd_evaluation_test.py -> object_detection-0.1/object_detection/utils\n",
      "Writing object_detection-0.1/setup.cfg\n",
      "creating dist\n",
      "Creating tar archive\n",
      "removing 'object_detection-0.1' (and everything under it)\n",
      "running sdist\n",
      "running egg_info\n",
      "creating slim.egg-info\n",
      "writing slim.egg-info/PKG-INFO\n",
      "writing dependency_links to slim.egg-info/dependency_links.txt\n",
      "writing top-level names to slim.egg-info/top_level.txt\n",
      "writing manifest file 'slim.egg-info/SOURCES.txt'\n",
      "reading manifest file 'slim.egg-info/SOURCES.txt'\n",
      "writing manifest file 'slim.egg-info/SOURCES.txt'\n",
      "running check\n",
      "warning: check: missing required meta-data: url\n",
      "\n",
      "warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied\n",
      "\n",
      "creating slim-0.1\n",
      "creating slim-0.1/datasets\n",
      "creating slim-0.1/deployment\n",
      "creating slim-0.1/nets\n",
      "creating slim-0.1/nets/mobilenet\n",
      "creating slim-0.1/nets/nasnet\n",
      "creating slim-0.1/preprocessing\n",
      "creating slim-0.1/slim.egg-info\n",
      "copying files to slim-0.1...\n",
      "copying README.md -> slim-0.1\n",
      "copying setup.py -> slim-0.1\n",
      "copying datasets/__init__.py -> slim-0.1/datasets\n",
      "copying datasets/build_imagenet_data.py -> slim-0.1/datasets\n",
      "copying datasets/build_visualwakewords_data.py -> slim-0.1/datasets\n",
      "copying datasets/build_visualwakewords_data_lib.py -> slim-0.1/datasets\n",
      "copying datasets/cifar10.py -> slim-0.1/datasets\n",
      "copying datasets/dataset_factory.py -> slim-0.1/datasets\n",
      "copying datasets/dataset_utils.py -> slim-0.1/datasets\n",
      "copying datasets/download_and_convert_cifar10.py -> slim-0.1/datasets\n",
      "copying datasets/download_and_convert_flowers.py -> slim-0.1/datasets\n",
      "copying datasets/download_and_convert_mnist.py -> slim-0.1/datasets\n",
      "copying datasets/flowers.py -> slim-0.1/datasets\n",
      "copying datasets/imagenet.py -> slim-0.1/datasets\n",
      "copying datasets/mnist.py -> slim-0.1/datasets\n",
      "copying datasets/preprocess_imagenet_validation_data.py -> slim-0.1/datasets\n",
      "copying datasets/process_bounding_boxes.py -> slim-0.1/datasets\n",
      "copying datasets/visualwakewords.py -> slim-0.1/datasets\n",
      "copying deployment/__init__.py -> slim-0.1/deployment\n",
      "copying deployment/model_deploy.py -> slim-0.1/deployment\n",
      "copying deployment/model_deploy_test.py -> slim-0.1/deployment\n",
      "copying nets/__init__.py -> slim-0.1/nets\n",
      "copying nets/alexnet.py -> slim-0.1/nets\n",
      "copying nets/alexnet_test.py -> slim-0.1/nets\n",
      "copying nets/cifarnet.py -> slim-0.1/nets\n",
      "copying nets/cyclegan.py -> slim-0.1/nets\n",
      "copying nets/cyclegan_test.py -> slim-0.1/nets\n",
      "copying nets/dcgan.py -> slim-0.1/nets\n",
      "copying nets/dcgan_test.py -> slim-0.1/nets\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "copying nets/i3d.py -> slim-0.1/nets\n",
      "copying nets/i3d_test.py -> slim-0.1/nets\n",
      "copying nets/i3d_utils.py -> slim-0.1/nets\n",
      "copying nets/inception.py -> slim-0.1/nets\n",
      "copying nets/inception_resnet_v2.py -> slim-0.1/nets\n",
      "copying nets/inception_resnet_v2_test.py -> slim-0.1/nets\n",
      "copying nets/inception_utils.py -> slim-0.1/nets\n",
      "copying nets/inception_v1.py -> slim-0.1/nets\n",
      "copying nets/inception_v1_test.py -> slim-0.1/nets\n",
      "copying nets/inception_v2.py -> slim-0.1/nets\n",
      "copying nets/inception_v2_test.py -> slim-0.1/nets\n",
      "copying nets/inception_v3.py -> slim-0.1/nets\n",
      "copying nets/inception_v3_test.py -> slim-0.1/nets\n",
      "copying nets/inception_v4.py -> slim-0.1/nets\n",
      "copying nets/inception_v4_test.py -> slim-0.1/nets\n",
      "copying nets/lenet.py -> slim-0.1/nets\n",
      "copying nets/mobilenet_v1.py -> slim-0.1/nets\n",
      "copying nets/mobilenet_v1_eval.py -> slim-0.1/nets\n",
      "copying nets/mobilenet_v1_test.py -> slim-0.1/nets\n",
      "copying nets/mobilenet_v1_train.py -> slim-0.1/nets\n",
      "copying nets/nets_factory.py -> slim-0.1/nets\n",
      "copying nets/nets_factory_test.py -> slim-0.1/nets\n",
      "copying nets/overfeat.py -> slim-0.1/nets\n",
      "copying nets/overfeat_test.py -> slim-0.1/nets\n",
      "copying nets/pix2pix.py -> slim-0.1/nets\n",
      "copying nets/pix2pix_test.py -> slim-0.1/nets\n",
      "copying nets/resnet_utils.py -> slim-0.1/nets\n",
      "copying nets/resnet_v1.py -> slim-0.1/nets\n",
      "copying nets/resnet_v1_test.py -> slim-0.1/nets\n",
      "copying nets/resnet_v2.py -> slim-0.1/nets\n",
      "copying nets/resnet_v2_test.py -> slim-0.1/nets\n",
      "copying nets/s3dg.py -> slim-0.1/nets\n",
      "copying nets/s3dg_test.py -> slim-0.1/nets\n",
      "copying nets/vgg.py -> slim-0.1/nets\n",
      "copying nets/vgg_test.py -> slim-0.1/nets\n",
      "copying nets/mobilenet/__init__.py -> slim-0.1/nets/mobilenet\n",
      "copying nets/mobilenet/conv_blocks.py -> slim-0.1/nets/mobilenet\n",
      "copying nets/mobilenet/mobilenet.py -> slim-0.1/nets/mobilenet\n",
      "copying nets/mobilenet/mobilenet_v2.py -> slim-0.1/nets/mobilenet\n",
      "copying nets/mobilenet/mobilenet_v2_test.py -> slim-0.1/nets/mobilenet\n",
      "copying nets/nasnet/__init__.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/nasnet.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/nasnet_test.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/nasnet_utils.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/nasnet_utils_test.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/pnasnet.py -> slim-0.1/nets/nasnet\n",
      "copying nets/nasnet/pnasnet_test.py -> slim-0.1/nets/nasnet\n",
      "copying preprocessing/__init__.py -> slim-0.1/preprocessing\n",
      "copying preprocessing/cifarnet_preprocessing.py -> slim-0.1/preprocessing\n",
      "copying preprocessing/inception_preprocessing.py -> slim-0.1/preprocessing\n",
      "copying preprocessing/lenet_preprocessing.py -> slim-0.1/preprocessing\n",
      "copying preprocessing/preprocessing_factory.py -> slim-0.1/preprocessing\n",
      "copying preprocessing/vgg_preprocessing.py -> slim-0.1/preprocessing\n",
      "copying slim.egg-info/PKG-INFO -> slim-0.1/slim.egg-info\n",
      "copying slim.egg-info/SOURCES.txt -> slim-0.1/slim.egg-info\n",
      "copying slim.egg-info/dependency_links.txt -> slim-0.1/slim.egg-info\n",
      "copying slim.egg-info/top_level.txt -> slim-0.1/slim.egg-info\n",
      "Writing slim-0.1/setup.cfg\n",
      "creating dist\n",
      "Creating tar archive\n",
      "removing 'slim-0.1' (and everything under it)\n"
     ]
    }
   ],
   "source": [
    "!bash object_detection/dataset_tools/create_pycocotools_package.sh /tmp/pycocotools\n",
    "!python setup.py sdist\n",
    "!(cd slim && python setup.py sdist)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1;33mWARNING:\u001b[0m The `gcloud ml-engine` commands have been renamed and will soon be removed. Please use `gcloud ai-platform` instead.\n",
      "Job [root_object_detection_diagrams_05_09_2019_23_52_26] submitted successfully.\n",
      "Your job is still active. You may view the status of your job with the command\n",
      "\n",
      "  $ gcloud ai-platform jobs describe root_object_detection_diagrams_05_09_2019_23_52_26\n",
      "\n",
      "or continue streaming the logs with the command\n",
      "\n",
      "  $ gcloud ai-platform jobs stream-logs root_object_detection_diagrams_05_09_2019_23_52_26\n",
      "jobId: root_object_detection_diagrams_05_09_2019_23_52_26\n",
      "state: QUEUED\n"
     ]
    }
   ],
   "source": [
    "!gcloud ml-engine jobs submit training `whoami`_object_detection_diagrams_`date +%m_%d_%Y_%H_%M_%S` \\\n",
    "    --runtime-version 1.12 \\\n",
    "    --job-dir=gs://$GCS_BUCKET/model_dir \\\n",
    "    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz \\\n",
    "    --module-name object_detection.model_main \\\n",
    "    --region us-central1 \\\n",
    "    --config /u01/notebooks/TFM/Configs/cloud.yml \\\n",
    "    -- \\\n",
    "    --model_dir=gs://$GCS_BUCKET/model_dir \\\n",
    "    --pipeline_config_path=gs://$GCS_BUCKET/data/rfcn_resnet101GCP.config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/u01/notebooks/models/research/dist\n"
     ]
    }
   ],
   "source": [
    "cd dist/\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "trainingInput:\r\n",
      "  runtimeVersion: \"1.12\"\r\n",
      "  scaleTier: CUSTOM\r\n",
      "  masterType: standard_gpu\r\n",
      "  workerCount: 5\r\n",
      "  workerType: standard_gpu\r\n",
      "  parameterServerCount: 3\r\n",
      "  parameterServerType: standard\r\n",
      "\r\n",
      "\r\n",
      "\r\n"
     ]
    }
   ],
   "source": [
    "!cat object_detection/samples/cloud/cloud.yml"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/u01/notebooks/TFM/DatasetCreator/out\n"
     ]
    }
   ],
   "source": [
    "cd /u01/notebooks/TFM/DatasetCreator/out/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "total 84736\r\n",
      "drwxr-xr-x 2 root root     4096 May  9 22:55 test\r\n",
      "-rw-r--r-- 1 root root 20244836 May  9 22:55 test.record\r\n",
      "drwxr-xr-x 2 root root    12288 May  9 22:55 train\r\n",
      "-rw-r--r-- 1 root root 66504422 May  9 22:55 train.record\r\n"
     ]
    }
   ],
   "source": [
    "!ls -l"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-05-10 00:06:55.026825: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 0.599995 seconds (attempt 1 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "TensorBoard 1.13.1 at http://9400d997ece8:6006 (Press CTRL+C to quit)\n",
      "2019-05-10 00:06:55.718597: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 0.193958 seconds (attempt 2 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:06:56.000271: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 0.380297 seconds (attempt 3 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:06:56.866604: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 0.508539 seconds (attempt 4 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:06:57.467039: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 1.05515 seconds (attempt 5 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:06:58.612262: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 0.535398 seconds (attempt 6 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:06:59.239236: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 1.22932 seconds (attempt 7 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:07:00.560225: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 1.3387 seconds (attempt 8 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:07:02.067810: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 1.4677 seconds (attempt 9 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:07:03.703376: I tensorflow/core/platform/cloud/retrying_utils.cc:73] The operation failed and will be automatically retried in 1.51926 seconds (attempt 10 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\n",
      "2019-05-10 00:07:05.314728: W tensorflow/core/platform/cloud/google_auth_provider.cc:157] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with \"Not found: Could not locate the credentials file.\". Retrieving token from GCE failed with \"Aborted: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'\".\n",
      "Exception in thread Reloader:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/threading.py\", line 917, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/root/anaconda3/lib/python3.7/threading.py\", line 865, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 389, in _reload\n",
      "    multiplexer.AddRunsFromDirectory(path, name)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 183, in AddRunsFromDirectory\n",
      "    for subdir in io_wrapper.GetLogdirSubdirectories(path):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/event_processing/io_wrapper.py\", line 179, in GetLogdirSubdirectories\n",
      "    if not tf.io.gfile.exists(path):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir\n",
      "\n",
      "E0510 00:07:05.807509 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:06.035136 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:07:06.310368 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:06.570565 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:08.570454 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:08.874733 140135067674368 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:09.092802 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:09.328729 140135067674368 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:09.544548 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:09.861583 140135067674368 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:10.060484 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:07:10.389091 140135067674368 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:38.613540 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:38.889686 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:39.172364 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:07:39.470485 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:08:08.621824 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:08.863870 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:09.152077 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:09.397992 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:38.581665 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:08:38.814156 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:39.111190 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:08:39.374390 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:08.684583 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:09.073991 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:09:09.353534 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:09.639951 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:38.727045 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:38.955902 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:09:39.240208 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E0510 00:09:39.533012 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:10:08.620046 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:10:08.858502 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:10:09.279439 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n",
      "E0510 00:10:09.539993 140135076067072 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 310, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/backend/application.py\", line 281, in _serve_plugins_listing\n",
      "    response[plugin.plugin_name] = plugin.is_active()\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder_plugin.py\", line 74, in is_active\n",
      "    return tf.io.gfile.exists(summary_filename) and\\\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 277, in file_exists_v2\n",
      "    pywrap_tensorflow.FileExists(compat.as_bytes(path), status)\n",
      "  File \"/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{\n",
      " \"error\": {\n",
      "  \"errors\": [\n",
      "   {\n",
      "    \"domain\": \"global\",\n",
      "    \"reason\": \"required\",\n",
      "    \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\",\n",
      "    \"locationType\": \"header\",\n",
      "    \"location\": \"Authorization\"\n",
      "   }\n",
      "  ],\n",
      "  \"code\": 401,\n",
      "  \"message\": \"Anonymous caller does not have storage.objects.get access to es_kiff/model_dir/plugins/beholder/frame.summary.\"\n",
      " }\n",
      "}\n",
      "'\n",
      "\t when reading metadata of gs://es_kiff/model_dir/plugins/beholder/frame.summary\n"
     ]
    }
   ],
   "source": [
    "!tensorboard --logdir=gs://es_kiff/model_dir"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
